### ISSUE TITLE
Missing a lot of generators - React, Gatsby, ... 

### ISSUE THREAD

**Issue by Brian-McBride** [etkachev/nx-webstorm#43]
## Current Behavior
The Generate list is missing generators from all the installed packages.
The ones that I am currently missing are:
`"@nrwl/gatsby": "^11.0.0",`
`"@nrwl/react": "11.1.5"`

Also, there is a `web` generator in the Visual Studio Code list that is missing from the Webstorm list. I don't use it, but I did notice it missing. 

## How to Reproduce
1. Install ALL the Nx plugins - just to have all the generators available
2. Open the project in VS Code with the Nx extension installed
3. Open up the project in Webstorm with the Nx Plugin installed
4. Compare the lists

## Expected Behavior
All generators of all types should be visible and executable within the Webstorm plugin

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Webstorm version 2020.3.1

## Additional context
Super handy tool.

**Comment by etkachev** [comment]
Hello @Brian-McBride! Thank you for posting. I can investigate and try to get back to you soon.

**Comment by etkachev** [comment]
Ok so I think it should be an easy update on your end.....

## Option 1

1. If you go to your webstorm preferences under `Tools -> Nx Plugin Settings -> External Schematics`, you should be able to add the missing packages to search under. See example of me adding those below:
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/9970746/105256615-ee596980-5b3a-11eb-928e-fce9abb1d107.png">
2. Once you add the missing ones (such as `@nrwl/react`, `@nrwl/gatsby`, `@nrwl/web`), when you refresh the list of schematics, they should show up:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/9970746/105256711-25c81600-5b3b-11eb-84f0-91d7e8b7246d.png">

## Option 2
1. If you go to your webstorm preferences under `Tools -> Nx Plugin Settings`, and turn off the setting that does the explicit scan, that should also automatically find all the schematics you may need.
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/9970746/105256840-64f66700-5b3b-11eb-9773-564b69eb6208.png">
2. With doing this option, I did notice sometimes it does not pick up all packages (like ones within hidden folders, like angular schematics sometimes are). Which is why it's safer to do the explicit scan route... Also doing explicit scan would be faster for projects that are much larger that have a lot more `node_modules` to scan.

## Side note
On that note, I can update the plugin to automatically include those extra package schematics to scan for, so if you prefer to do the `Explicit scan` route, you wouldn't have to always add those explicit packages on any new project.

Let me know if any of these options solve your case, and let me know if you have any further questions.

**Comment by etkachev** [comment]
Closing since defaults has been added to latest 0.8.0 release. Any other missing packages can be added manually through settings. Let me know if you have any further questions on this. Thanks
