### ISSUE TITLE
Use kebab-case because the other is depraced for options

### ISSUE THREAD

**Issue by adambrangenberg** [etkachev/nx-webstorm#94]
## How to Reproduce
Steps to reproduce the behavio**u**r:
1. Use the latest Angular Version
2. Generate a new Component
3. Check inlineStyle or something different
4. Run it and look at the console

## Expected Behavio**u**r
To use the new way of adding options, so it won't break in the next Angular version

## Screenshots
![image](https://user-images.githubusercontent.com/69903408/168656947-daaf60fc-acf5-40ea-bad6-441aba822bd1.png)

**Comment by LuisTovar0** [comment]
This makes the plugin unusable in recent Angular CLI versions because of the deprecation of camel case flags ([see](https://plugins.jetbrains.com/plugin/15000-nx-console-ui/reviews#review=78581)).
![image](https://user-images.githubusercontent.com/72473883/215448010-d84e15bd-0946-483a-a675-fbd9384ee994.png)

The reason is that the plugin reads the command schematic's `schema.json` (f.e. [`node_modules/@schematics/angular/component/schema.json`](https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/component/schema.json) for `ng generate command`) to figure out the command's flags and their characteristics. However, the command names in the `shcema.json` file no longer match the ones in the [documentation](https://angular.io/cli/generate#component-command).

However, I believe that this strategy can still be viable if a couple of tweaks are added. I searched through the [Angular CLI repo](https://github.com/angular/angular-cli/) to try to find where the kebab-case commands are, but couldn't find them, because they just "dasherize" (convert camelCase to kebab-case) the commands found in the `schema.json` files (I didn't find where the dasherization happens, but I'm 99% sure it happens somewhere).

That can be part of the **possible solution**:
+ the plugin figures out if the user's Angular CLI version requires kebab-case. I looked a bit into how this can be achieved, by searching for any flags that the CLI uses to figure out if it should allow camelCase flags ([here](https://github.com/angular/angular-cli/blob/577bee321314bf55b11b7ebfd252ef5bcd8eeadb/packages/angular/cli/models/parser.ts#L216)), but didn't find anything. So... the remaining option seems to be hard-coding a map that specifies which versions require/recommend kebab-case usage
+ if kebab-case is recommended, dasherize the camelCase flags found in the `schema.json`

**Comment by etkachev** [comment]
Thanks! Yea I'll have to look into why angular would have their schema.json not match what the cli is expecting for the generators. Assuming you guys are setup with just plain angular project and not within nx?

**Comment by TigerbyteDev** [comment]
I also was on plain Angular

**Comment by vKxni** [comment]
hi

**Comment by etkachev** [comment]
I also wanted to let you know about slowly deprecating this plugin in favor for the official on by Nrwl: https://plugins.jetbrains.com/plugin/21060-nx-console

**Comment by adambrangenberg** [comment]
Should I close the issue then?
