### ISSUE TITLE
Incompatible with version WebStorm 2022.3

### ISSUE THREAD

**Issue by elicul** [etkachev/nx-webstorm#99]
## Current Behavior
Unable to use on WebStorm 2022.3.

## How to Reproduce
1. Download the latest WebStorm IDE (2022.3)
2. Open WebStorm a notification will appear that nx-webstorm is incompatible 

## Expected Behavior
nx-webstorm should be compatible with that version.

## Screenshots
![image](https://user-images.githubusercontent.com/16355755/204475273-e399e80a-99e2-4abf-b4eb-103acd6a4064.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Webstorm version [2022.3]

## Additional context
If you need any help in testing please let me know.

**Comment by etkachev** [comment]
Thanks! In the process of updating compatibility. Will keep you posted.

**Comment by etkachev** [comment]
This should be now updated and published in the marketplace. Not sure if it will just automatically update for you, but I was required to update the name (because prior it included the name webstorm). You should be able to see the 0.13.0 version now. https://plugins.jetbrains.com/plugin/15000-nx-console-ui/

Let me know if you have any other questions
